//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_soap_client.soapsvtest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://soap.testsv.jp/", ConfigurationName="soapsvtest.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 名前空間 https://soap.testsv.jp/ の要素名 HelloWorldResult が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="https://soap.testsv.jp/HelloWorld", ReplyAction="*")]
        test_soap_client.soapsvtest.HelloWorldResponse HelloWorld(test_soap_client.soapsvtest.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://soap.testsv.jp/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<test_soap_client.soapsvtest.HelloWorldResponse> HelloWorldAsync(test_soap_client.soapsvtest.HelloWorldRequest request);
        
        // CODEGEN: 名前空間 https://soap.testsv.jp/ の要素名 input が nillable に設定されていないため、メッセージ コントラクトを生成しています
        [System.ServiceModel.OperationContractAttribute(Action="https://soap.testsv.jp/AddQuote", ReplyAction="*")]
        test_soap_client.soapsvtest.AddQuoteResponse AddQuote(test_soap_client.soapsvtest.AddQuoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://soap.testsv.jp/AddQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<test_soap_client.soapsvtest.AddQuoteResponse> AddQuoteAsync(test_soap_client.soapsvtest.AddQuoteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="https://soap.testsv.jp/", Order=0)]
        public test_soap_client.soapsvtest.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(test_soap_client.soapsvtest.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="https://soap.testsv.jp/", Order=0)]
        public test_soap_client.soapsvtest.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(test_soap_client.soapsvtest.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://soap.testsv.jp/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddQuoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddQuote", Namespace="https://soap.testsv.jp/", Order=0)]
        public test_soap_client.soapsvtest.AddQuoteRequestBody Body;
        
        public AddQuoteRequest() {
        }
        
        public AddQuoteRequest(test_soap_client.soapsvtest.AddQuoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://soap.testsv.jp/")]
    public partial class AddQuoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public AddQuoteRequestBody() {
        }
        
        public AddQuoteRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddQuoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddQuoteResponse", Namespace="https://soap.testsv.jp/", Order=0)]
        public test_soap_client.soapsvtest.AddQuoteResponseBody Body;
        
        public AddQuoteResponse() {
        }
        
        public AddQuoteResponse(test_soap_client.soapsvtest.AddQuoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://soap.testsv.jp/")]
    public partial class AddQuoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddQuoteResult;
        
        public AddQuoteResponseBody() {
        }
        
        public AddQuoteResponseBody(string AddQuoteResult) {
            this.AddQuoteResult = AddQuoteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : test_soap_client.soapsvtest.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<test_soap_client.soapsvtest.WebService1Soap>, test_soap_client.soapsvtest.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_soap_client.soapsvtest.HelloWorldResponse test_soap_client.soapsvtest.WebService1Soap.HelloWorld(test_soap_client.soapsvtest.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            test_soap_client.soapsvtest.HelloWorldRequest inValue = new test_soap_client.soapsvtest.HelloWorldRequest();
            inValue.Body = new test_soap_client.soapsvtest.HelloWorldRequestBody();
            test_soap_client.soapsvtest.HelloWorldResponse retVal = ((test_soap_client.soapsvtest.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_soap_client.soapsvtest.HelloWorldResponse> test_soap_client.soapsvtest.WebService1Soap.HelloWorldAsync(test_soap_client.soapsvtest.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_soap_client.soapsvtest.HelloWorldResponse> HelloWorldAsync() {
            test_soap_client.soapsvtest.HelloWorldRequest inValue = new test_soap_client.soapsvtest.HelloWorldRequest();
            inValue.Body = new test_soap_client.soapsvtest.HelloWorldRequestBody();
            return ((test_soap_client.soapsvtest.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_soap_client.soapsvtest.AddQuoteResponse test_soap_client.soapsvtest.WebService1Soap.AddQuote(test_soap_client.soapsvtest.AddQuoteRequest request) {
            return base.Channel.AddQuote(request);
        }
        
        public string AddQuote(string input) {
            test_soap_client.soapsvtest.AddQuoteRequest inValue = new test_soap_client.soapsvtest.AddQuoteRequest();
            inValue.Body = new test_soap_client.soapsvtest.AddQuoteRequestBody();
            inValue.Body.input = input;
            test_soap_client.soapsvtest.AddQuoteResponse retVal = ((test_soap_client.soapsvtest.WebService1Soap)(this)).AddQuote(inValue);
            return retVal.Body.AddQuoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_soap_client.soapsvtest.AddQuoteResponse> test_soap_client.soapsvtest.WebService1Soap.AddQuoteAsync(test_soap_client.soapsvtest.AddQuoteRequest request) {
            return base.Channel.AddQuoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_soap_client.soapsvtest.AddQuoteResponse> AddQuoteAsync(string input) {
            test_soap_client.soapsvtest.AddQuoteRequest inValue = new test_soap_client.soapsvtest.AddQuoteRequest();
            inValue.Body = new test_soap_client.soapsvtest.AddQuoteRequestBody();
            inValue.Body.input = input;
            return ((test_soap_client.soapsvtest.WebService1Soap)(this)).AddQuoteAsync(inValue);
        }
    }
}
